### ISSUE TITLE
Pingone Assuming role : Failed to assume role, please check whether you are permitted to assume the given role for the AWS service

### ISSUE THREAD

**Issue by shashidharrao** [Versent/saml2aws#523] opened 2020-07-17 17:52 UTC
type=saml-response
missing Response element
error parsing destination url
github.com/versent/saml2aws/cmd/saml2aws/commands.resolveRole
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:226
github.com/versent/saml2aws/cmd/saml2aws/commands.selectAwsRole
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:204
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:90
main.main
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:151
runtime.main
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373
Failed to assume role, please check whether you are permitted to assume the given role for the AWS service
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:92
main.main
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:151
runtime.main
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373

**Comment by shashidharrao** [comment] 2020-07-17 17:54
I was able to get the SAML response but not able to get the roles to select after the response. If we get the list of roles then we can chose out one. but not able get the roles after signing in.

**Comment by tbugfinder** [comment] 2020-07-21 16:59
Hi,
I have the same issue however on Windows and running behind corp proxy.
No issues though, while using same configuration on Linux.

**Comment by tbugfinder** [comment] 2020-07-21 17:11
I've added `--verbose`:
Login finished successfully, AWS sends the list to choose the role off and the the client errors out with:
```
missing Response element
error parsing destination url
github.com/versent/saml2aws/cmd/saml2aws/commands.resolveRole
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:226
github.com/versent/saml2aws/cmd/saml2aws/commands.selectAwsRole
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:204
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:90
main.main
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:163
runtime.main
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373
Failed to assume role, please check whether you are permitted to assume the given role for the AWS service
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:92
main.main
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:163
runtime.main
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373

```

**Comment by tbugfinder** [comment] 2020-07-21 17:13
If I add a specific role using `--role=.......` the error is the same.

**Comment by shashidharrao** [comment] 2020-07-21 17:24
@tbugfinder  thank you for responding. I am running it from Linux machine but it's behind a proxy. do you think proxy is the issue ??

**Comment by shashidharrao** [comment] 2020-07-21 17:28
it's not working when i try the same from windows machine from corp network.

PS C:\Users\shashi> saml2aws login
Using IDP Account default to access PingOne https://sso.*******.com/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices
To use saved password just hit enter.
? Username shashia
? Password **********

Authenticating as shashia...
error authenticating to IdP: error following: request for url: https://sso.*****.com/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices failed status: **401 Unauthorized**

**Comment by tbugfinder** [comment] 2020-07-21 17:44
Linux works good for me.

**Comment by tbugfinder** [comment] 2020-07-21 17:45
Which is your configuration, client version and command you are executing?

**Comment by tbugfinder** [comment] 2020-07-21 18:08
I just downloaded v2.25.0 and this works perfectly for my Windows environment.
Please also note that I'm using 2.25.0 on my Linux box.
@shashidharrao Would you give that version a try?

**Comment by shashidharrao** [comment] 2020-07-21 19:12
v2.25.0  worked fine. thanks for the inputs. appreciate your help on this.

**Comment by tie624** [comment] 2020-09-25 16:12
Here's what I found after some digging in the code:
In v2.26.0, a method was added to get the sign-in URL from the SAMLResponse rather than hardcoding it. The method is **ExtractDestinationURL**. The URL used to be hardcoded to https://signin.aws.amazon.com/saml.

The issue is that the SAMLResponse doesn't always contain a destination, which triggers an error message from **ExtractDestinationURL**.

I think **ExtractDestinationURL** should return https://signin.aws.amazon.com/saml as a default if the destination attribute does not exist in the SAMLResponse.

**Comment by tie624** [comment] 2020-09-25 17:27
Looks like this problem was also mentioned in issue #494

**Comment by dhivagit** [comment] 2020-10-15 15:08
Is there any fix for this issue? I am still getting this error while executing saml2aws login in my Ubuntu Linux (version 2.27.1).
But when I set --skip-verify flag, its working fine.

**Comment by tie624** [comment] 2020-10-16 22:27
> Is there any fix for this issue? I am still getting this error while executing saml2aws login in my Ubuntu Linux (version 2.27.1).
> But when I set --skip-verify flag, its working fine.

I don't what you are experiencing is the same issue. Your issue sounds like a server certificate issue. This one is the destination attribute not being in the SAML Response.

**Closed** 2020-11-10 11:07 UTC
