### ISSUE TITLE
Azure AD Number Match MFA

### ISSUE THREAD

**Issue by dannykitchen** [Versent/saml2aws#843] opened 2022-07-01 15:49 UTC
Azure AD Auth SSO - Microsoft soon to enforce number match 
https://docs.microsoft.com/en-us/azure/active-directory/authentication/how-to-mfa-number-match

Currently not supported 
Can you advise if will be covered ?

**Comment by ablackrw** [comment] 2022-11-18 15:42
It appears that a patch has been proposed to implement this matching as #857, but the change just seems to be sitting there. We are looking to roll out number matching in our MFA environment, and this lack of support is forming an impediment to the roll out.

**Comment by ablackrw** [comment] 2022-12-05 19:58
As a followup on my last comment, the change proposed in #857 is for ADFS, not AAD. I've put forward a patch for AAD support as #921, though I've only had limited success testing due to unrelated issues.

**Comment by edgranau** [comment] 2023-02-16 00:59
any updates on support for this? Number matching got activated in my client's org and `s2a` stopped working for me :( https://petri.com/microsoft-authenticator-number-matching-by-default/

**Comment by sammcj** [comment] 2023-02-16 01:06
Confirming saml2aws is now broken due to this.

**Comment by sammcj** [comment] 2023-02-16 02:47
Seeing the fallout from this today highlights to me what a critical piece of software this is. I wish AWS would either support it - or provide an official alternative.

**Comment by johnfilo-kmart** [comment] 2023-02-16 06:29
Yes, the issue is with AAD not ADFS. The ADFS changes were already merged (#857)

**Comment by ajohanssonwalder** [comment] 2023-02-20 02:21
This has been resolved by https://github.com/Versent/saml2aws/pull/829, incorporated into latest release [v2.36.3](https://github.com/Versent/saml2aws/releases/tag/v2.36.3) 🚀

**Closed** 2023-02-20 02:22 UTC
