### ISSUE TITLE
New feature: Briefly caching SAML Assertions

### ISSUE THREAD

**Issue by danopia** [Versent/saml2aws#526] opened 2020-07-22 14:22 UTC
I'm interested in caching of the full SAML assertion that is received from the IDP. I could contribute a PR for this, just wanted to open a ticket first to gather agreement on approach, storage location, enablement strategy, etc.

I'm using the OneLogin provider, and their API does not allow for reusing a MFA'd session, so each SAML flow requires a fresh MFA code. However the OneLogin SAML assertions themselves are valid for **6 minutes**.

During this window the SAML assertion can be sent to AWS repeatedly to create multiple sessions to different AWS accounts and AWS roles. After it expires then it needs to just be thrown away and the user prompted to perform a fresh login flow.

This cache wouldn't be as long-lived as a proper IDP session cache (as requested in #492) however it should work the same way with every SAML provider so it should be immediately usable by anyone, not just users of a certain provider.

As far as implementation, I think placing the assertion on disk (as opposed to keychain) makes sense due to its larger size and short livespan. OneLogin's own CLI tool [added SAML caching](https://github.com/onelogin/onelogin-python-aws-assume-role/commit/9e8137b7606d315ea1c491c093e689e38c5a16b3) as an opt-in feature and stores the body at `$HOME/.aws/saml_cache.txt` (saml2aws would likely want to use a dynamic filename that includes the provider config name, if filesystem is used)

**Comment by danopia** [comment] 2020-08-19 07:15
Here's a diff for a first pass, which I've been using for a couple weeks now just fine, but which also lacks configurability. It always performs caching. https://github.com/Versent/saml2aws/compare/master...danopia:saml-caching

**Comment by max-rocket-internet** [comment] 2021-02-12 08:40
We would also love this feature for the same reason: we have the same IDP for many AWS accounts

We also implemented our own solution in a fork but it would be great to get something merged.

Other issues for the same feature:
https://github.com/Versent/saml2aws/issues/438
https://github.com/Versent/saml2aws/issues/492

@wolfeidau any idea how we can move forwards? Should we open a PR?

**Comment by sledigabel** [comment] 2021-02-12 08:57
I've implemented this locally, this is easily doable I think;
I'll file a PR today.

**Comment by danopia** [comment] 2021-02-12 20:49
Nice to see some attention here. I'd like to clarify though as I already mentioned #492 in my original message. I believe it is requesting caching/reuse of a different part of the login flow.

My request here + linked patch set stores the full SAML assertion for as-is reuse, which can theoretically be used for any SAML provider, for a short period of time. I'm using OneLogin which sets this period of time to 6 minutes.

I understand #462 as requesting caching of identity provider sessions when possible. It sounds like Okta has a session cookie that would enable getting a fresh SAML assertion later in the same day without providing another MFA code. OneLogin does not support this in their API which makes it a non starter to my org.

Given that these two types of cache could even be used together if both were implemented, I think it would be useful to clarify which type of caching is being discussed 😌

**Comment by sledigabel** [comment] 2021-02-13 11:23
Hi @danopia,

Great point indeed,
I've tentatively filed PR #607 to address specifically the SAML assertion caching.
The `provider` interface makes it quite generic to do this at this level.

If that's headed in the right direction, I can polish it a little.
Tested it with adfs2, it seems to work fine and makes it easy to loop over list-roles and perform subsequent logins without having to perform the MFA each time.

**Comment by sledigabel** [comment] 2021-03-01 11:29
I pushed #607 for review, any chance someone could try this with different providers and different platforms?
tested successfully on a mac with ADFS

**Closed** 2021-03-11 18:12 UTC

**Comment by max-rocket-internet** [comment] 2021-03-12 15:48
@sledigabel we have the same IdP but many AWS accounts, same as OP. We have a `saml2aws` profile per AWS account. Is it possible to use your feature to use the same SAML assertian across multiple `saml2aws` profiles? Because I tested it and it didn't work, unless I'm making some mistake.

All profiles have `saml_cache = true` in `~/.saml2aws`.

I auth to the first profile with `saml2aws --skip-prompt login -a profile1`, then I see the creation of `~/.aws/saml2aws/cache_profile1`, cool. But I want to reuse that assertian for `profile2` but this doesn't work. Interestingly, I can copy `~/.aws/saml2aws/cache_profile1` to `~/.aws/saml2aws/cache_profile2` and then it works.

**Comment by max-rocket-internet** [comment] 2021-03-12 15:51
Perhaps we could cache the assertian to `~/.aws/saml2aws/cache_<provider>`? Then any saml2aws profile that has the same `provider` name in `~/.saml2aws` would use the same cache.

**Comment by sledigabel** [comment] 2021-03-12 16:23
I'm not sure what you mean @max-rocket-internet, would love to dig into it.
Typically with ADFS, I get a list of roles from certain AWS accounts my user can assume. It's done through a single provider. Then i break them down at the aws config level, where a profile is accessed through that single provider again.

I can confirm that the saml assertion will not work across idp accounts. This would not be a typical use case I think (though I might be biaised on this, happy to be convinced otherwise), for all we know they could be completely different users, environments, roles.
You can probably hack this using a symlink. if you link `~/.aws/saml2aws/cache_profile2` to point to `~/.aws/saml2aws/cache_profile1` it should work.

**Comment by sledigabel** [comment] 2021-03-12 16:25
> Perhaps we could cache the assertian to `~/.aws/saml2aws/cache_<provider>`? Then any saml2aws profile that has the same `provider` name in `~/.saml2aws` would use the same cache.

To answer this specifically, I don't think it would be an intuitive behaviour. I could have 2 separate accounts in two completely separate environment, I would not expect out of the box my SAML assertion from one to be used in the other.

**Comment by max-rocket-internet** [comment] 2021-03-12 16:52
> I get a list of roles from certain AWS accounts my user can assume.

You mean multiple roles, per AWS account? Or a roles per account and many AWS accounts (our situation)?

> I can confirm that the saml assertion will not work across idp accounts.

I don't mean across mulitple IdPs, of course that won't work, I mean a single IdP but multiple AWS accounts 🙂

To be clear: we use Keycloak, it's our single IdP. We have a single user in Keycloak, we auth to keycloak to get an SAML assertian. But we have many AWS accounts, all using the same Keycloak IdP. Every saml2aws profile has the same `url/provider`

>  for all we know they could be completely different users, environments, roles.

Same user, same assertian but can be used to many AWS accounts because they all trust this single IdP.

> You can probably hack this using a symlink

I'd rather not 😃

> To answer this specifically, I don't think it would be an intuitive behaviour.

I think it is because if the `provider` and `url` are the same then it's the same IdP? And that is the perfect usecase to use cache?

I think what I'm describing here is what @danopia described in the issue text:

> However the OneLogin SAML assertions themselves are valid for 6 minutes.
> During this window the SAML assertion can be sent to AWS repeatedly to create multiple sessions to different AWS accounts and AWS roles.

**Comment by max-rocket-internet** [comment] 2021-03-12 17:00
Maybe this helps?

```
[profile1]
app_id               =
url                  = https://keycloak.my-company.com/auth/realms/aws/protocol/saml/clients/amazon-aws
provider             = KeyCloak
mfa                  = Auto
skip_verify          = true
timeout              = 0
aws_urn              = urn:amazon:webservices
aws_session_duration = 43200
aws_profile          = profile1
resource_id          =
subdomain            =
role_arn             = arn:aws:iam::666666666:role/my-role-admin
region               =
http_attempts_count  =
http_retry_delay     =
saml_cache           = true

[profile2]
app_id               =
url                  = https://keycloak.my-company.com/auth/realms/aws/protocol/saml/clients/amazon-aws
provider             = KeyCloak
mfa                  = Auto
skip_verify          = true
timeout              = 0
aws_urn              = urn:amazon:webservices
aws_session_duration = 43200
aws_profile          = profile2
resource_id          =
subdomain            =
role_arn             = arn:aws:iam::33333333333:role/my-role-admin
region               =
http_attempts_count  =
http_retry_delay     =
saml_cache           = true
```

Cache from either of these profiles should work for the other. Or perhaps is my config not correct?

**Comment by sledigabel** [comment] 2021-03-12 17:36
Yeah I get it now. Thanks for clarifying your use case.
From the `saml2aws` point of view you've configured them as different providers. They can't share the SAML assertion.

I think we are in the same scenario, really, except you use IdP providers to switch between roles.
I _think_ the role arn here was to put a default option for a given provider but assumed to be overridden at login time if you need to assume another role.

I need to think more about it, so far I've used `credential_process` that's simplifying this very use case for me where i don't have to invoke `saml2aws` each time i log in under the same idp provider. Perhaps we could add on an option to use a common cache file? or override the path of each cache for each profile?

curious to see what @wolfeidau thinks too on this and everyone else to see whether this is a common use case.

**Comment by sledigabel** [comment] 2021-03-12 18:04
Been thinking that federations based on endpoint would not necessarily work either. You could have two completely different users to the same endpoints that would fetch entirely different role sets.

I've got an embryo of an idea...
Perhaps changing the cli so that each saml2aws profile can be specified its cache file destination would work for everyone; by default they would be separated but you can force all of them to use the same file.

Would that work @max-rocket-internet ?

**Comment by max-rocket-internet** [comment] 2021-03-15 10:10
Hi @sledigabel 

> Yeah I get it now. Thanks for clarifying your use case.

Great!

> Perhaps changing the cli so that each saml2aws profile can be specified its cache file destination would work for everyone; by default they would be separated but you can force all of them to use the same file.

Yes, I think that would work. That's more or less what I suggested with:

> Perhaps we could cache the assertian to ~/.aws/saml2aws/cache_<provider>? Then any saml2aws profile that has the same provider name in ~/.saml2aws would use the same cache.

This puts some pressure on the user, they must not use the same `provider = XXX` across different profiles (when using cache) unless those profiles are using the same IdP.

Or we could have an option like `saml_cache = <by_profile|by_provider>`? It would be nice not to have to specify file names.

**Comment by sledigabel** [comment] 2021-03-15 10:37
awesome, I'll get to work :-)

I get your point about adding some cognitive load to the user, but I'd argue It gets tricky on the cli level to have groupings, might as well just override the whole thing. This could be easily templated outside of the configure step too.

It _feels_ like from a behavioural point of view, we'd make the cli use the default name (one per provider) or a specific file then you're free to use it however you want agnostically of the specific use case where the same cache file is used across providers, that could be adding some accidental complexity. In terms of consistency with the cli options, it works better too (you could configure one but override it at login time for whatever reason).

Like I said before, you have also the use case where you could have the same provider, same endpoint but different usernames and passwords. (having said that, i'm not sure how that would work with the credentials, not sure they are provider dependant. i'll look by curiosity).

Let me know if there's a red flag in my reasoning, and we can still add the groupings later if that's required.

Thanks for bearing with me :-)

**Comment by max-rocket-internet** [comment] 2021-03-15 12:32
>  I'd argue It gets tricky on the cli level to have groupings, might as well just override the whole thing

Cool

> In terms of consistency with the cli options, it works better too

Cool

> you have also the use case where you could have the same provider, same endpoint but different usernames and passwords

Make sense but in this case I think the user just has to use a different name for the `provider` in their config file.

> i'm not sure how that would work with the credentials

It wouldn't work.

> Let me know if there's a red flag in my reasoning, and we can still add the groupings later if that's required.

All good. As long as we can have cache across profiles I don't really mind how it's implemented. If we need to specify the same cache file in multiple profiles then also fine.

> Thanks for bearing with me :-)

I'm just writing messages, you're doing the actual work. So thank YOU 💛

**Comment by sledigabel** [comment] 2021-03-16 17:51
@max-rocket-internet PR is filed here: https://github.com/Versent/saml2aws/pull/634

**Comment by danopia** [comment] 2021-03-17 07:54
Interesting discussion here..

My org documentation says to configure the IdP once in saml2aws, with a fixed default role reasonable for development, and then copy qualified statements to use other roles:

> Copy/paste one of these standard commands to access a specific role/account combination using consistent naming:
>
> ```
> # ReadOnly roles let you look at everything, without making unintended changes
> saml2aws login --profile dev-ReadOnly --role arn:aws:iam::xx:role/SSOReadOnly
> saml2aws login --profile prod-ReadOnly --role arn:aws:iam::yy:role/SSOReadOnly
> saml2aws login --profile mgmt-ReadOnly --role arn:aws:iam::zz:role/SSOReadOnly
> 
> # Developer roles allow engineers to manage common resources
> saml2aws login --profile dev-Developer --role arn:aws:iam::xx:role/SSODeveloper
> saml2aws login --profile prod-Developer --role arn:aws:iam::yy:role/SSODeveloper
> saml2aws login --profile mgmt-Developer --role arn:aws:iam::zz:role/SSODeveloper
> 
> # Admin roles are everything
> saml2aws login --profile dev-Admin --role arn:aws:iam::xx:role/SSOAdmin
> saml2aws login --profile prod-Admin --role arn:aws:iam::yy:role/SSOAdmin
> saml2aws login --profile mgmt-Admin --role arn:aws:iam::zz:role/SSOAdmin

So as far as I can tell the original #607 implements enough here and I'll be use it, thanks for the work here 👏

**Comment by max-rocket-internet** [comment] 2021-03-17 15:09
@danopia 

> So as far as I can tell the original #607 implements enough here and I'll be use it

But as far as I can see, none of your listed `saml2aws` commands there would use the cache as they all use different profiles 🙂

**Comment by danopia** [comment] 2021-03-17 16:18
No, #607 caches by saml2aws config name, not destination `AWS_PROFILE`. The usage I explained above only involves one saml2aws IDP config. I've upgraded to 2.28.4 and see my SAML assertions being cached to `~/.aws/saml2aws/cache_default`, and being reused correctly. LGTM

**Comment by sledigabel** [comment] 2021-03-17 16:19
> @danopia
> 
> > So as far as I can tell the original #607 implements enough here and I'll be use it
> 
> But as far as I can see, none of your listed `saml2aws` commands there would use the cache as they all use different profiles 🙂

I think it would @max-rocket-internet , that was my scenario earlier. `-p` or `--profile` are just a way to access AWS profiles, and that will store the credentials under a different section of the credentials file. `-a` would switch providers.
It looks like @danopia has a single provider, and multiple AWS profiles of the back of that.

Your use case is using providers to simplify the role switch and don't want to have to manage the `--role` and to a degree the `--profile` complexity.
There's definitely room for both, it's good to have flexibility there.

**Comment by max-rocket-internet** [comment] 2021-03-18 14:59
> I think it would @max-rocket-internet

> No, #607 caches by saml2aws config name, 

Ah yes, you are both right, I was conflating AWS profile and saml2aws profile.
