### ISSUE TITLE
[AzureAD] Seems AzureAD login procedure goes alright but returns `Response did not contain a valid SAML assertion`

### ISSUE THREAD

**Issue by adamist521** [Versent/saml2aws#351] opened 2019-09-26 00:48 UTC
I have a problem logging with Azure AD.
From the dumped result, it seems that login procedure looks successful from the token(cookies seems related to auth which I see when I look into browser session) showing but shows `Response did not contain a valid SAML assertion`.
Haven't looked into code yet but has anyone surpassed this issue?

Looks it was different to #350 from the dumped result so I posted new Issue.

I have attached DUMP result at following. (masked token with `******`, removed JS code seemed unrelated. JSON is formatted also.)

```
$ DUMP_CONTENT=true saml2aws login --verbose
DEBU[0000] Running                                       command=login
DEBU[0000] check if Creds Exist                          command=login
DEBU[0000] Expand                                        name=/Users/xxxxxxx/.aws/credentials pkg=awsconfig
DEBU[0000] resolveSymlink                                name=/Users/xxxxxxx/.aws/credentials pkg=awsconfig
DEBU[0000] ensureConfigExists                            filename=/Users/xxxxxxx/.aws/credentials pkg=awsconfig
Using IDP Account default to access AzureAD https://account.activedirectory.windowsazure.com
DEBU[0000] Get credentials                               helper=osxkeychain serverURL="https://account.activedirectory.windowsazure.com"
DEBU[0000] Get credentials                               goMsg="The specified item could not be found in the keychain." helper=osxkeychain
To use saved password just hit enter.
? Username <*emailaddress*>
? Password ********

DEBU[0005] building provider                             command=login idpAccount="account {\n  AppID: <*AppID*>\n  URL: https://account.activedirectory.windowsazure.com\n  Username: <*emailaddress*>\n  Provider: AzureAD\n  MFA: Auto\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 3600\n  Profile: saml\n  RoleARN: \n}"
Authenticating as <*emailaddress*> ...
POST /common/login HTTP/1.1
Host: login.microsoftonline.com
User-Agent: saml2aws/1.0 (darwin amd64) Versent
Content-Length: 1375
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

ctx=rQIIAZW******&flowToken=AQABA******&login=<*emailaddress*>&passwd=<*password*>
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
Content-Type: text/html; charset=utf-8
Date: Thu, 26 Sep 2019 00:11:25 GMT
Expires: -1
Link: <https://aadcdn.msftauth.net>; rel=preconnect; crossorigin
Link: <https://aadcdn.msftauth.net>; rel=dns-prefetch
Link: <https://aadcdn.msauth.net>; rel=dns-prefetch
P3p: CP="DSP CUR OTPi IND OTRi ONL FIN"
Pragma: no-cache
Set-Cookie: ESTSAUTHPERSISTENT=AQABA******; domain=.login.microsoftonline.com; expires=Wed, 25-Dec-2019 00:11:25 GMT; path=/; secure; HttpOnly
Set-Cookie: ESTSAUTH=AQABAA*******; domain=.login.microsoftonline.com; path=/; secure; HttpOnly
Set-Cookie: ESTSAUTHLIGHT=+600d0*******; path=/; secure
Set-Cookie: ch=1zlSHC****;
Set-Cookie: ESTSSC=00; path=/; secure; HttpOnly
Set-Cookie: buid=AQABAAE*****; expires=Sat, 26-Oct-2019 00:11:25 GMT; path=/; secure; HttpOnly
Set-Cookie: fpc=AoUMSA******; expires=Sat, 26-Oct-2019 00:11:25 GMT; path=/; secure; HttpOnly
Set-Cookie: x-ms-gateway-slice=prod; path=/; secure; HttpOnly
Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Dns-Prefetch-Control: on
X-Frame-Options: DENY
X-Ms-Ests-Server: 2.1.9395.17 - SIN2 ProdSlices
X-Ms-Request-Id: 4ea681f*********



<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->
<!DOCTYPE html>
<html dir="ltr" class="" lang="en">
<head>
    <title>Sign in to your account</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <link rel="preconnect" href="https://aadcdn.msftauth.net" crossorigin>
<meta http-equiv="x-dns-prefetch-control" content="on">
<link rel="dns-prefetch" href="//aadcdn.msftauth.net">
<link rel="dns-prefetch" href="//aadcdn.msauth.net">

    <meta name="PageID" content="KmsiInterrupt" />
    <meta name="SiteID" content="" />
    <meta name="ReqLC" content="1033" />
    <meta name="LocLC" content="en-US" />

        <meta name="referrer" content="origin" />

    <noscript>
        <meta http-equiv="Refresh" content="0; URL=https://login.microsoftonline.com/jsdisabled" />
    </noscript>


        <link rel="shortcut icon" href="https://aadcdn.msftauth.net/ests/2.1/content/images/favicon_a_eupayfgghqiai7k9sol6lg2.ico" />

    <meta name="robots" content="none" />

<script type="text/javascript">//<![CDATA[
$Config={ 
   "iMaxStackForKnockoutAsyncComponents":10000,
   "fShowButtons":true,
   "urlCdn":"https://aadcdn.msftauth.net/ests/2.1/",
   "urlFooterTOU":"https://www.microsoft.com/en-US/servicesagreement/",
   "urlFooterPrivacy":"https://privacy.microsoft.com/en-US/privacystatement",
   "urlPost":"/kmsi",
   "iPawnIcon":0,
   "sPOST_Username":"<*emailaddress*>",
   "sFT":"AQABAA**********",
   "sFTName":"flowToken",
   "sCtx":"rQIIAZ******",
   "sCanaryTokenName":"canary",
   "dynamicTenantBranding":null,
   "oAppCobranding":{ 

   },
   "iBackgroundImage":0,
   "fUseConstantPolling":true,
   "fUseFlowTokenAsCanary":true,
   "fApplicationInsightsEnabled":false,
   "iApplicationInsightsEnabledPercentage":0,
   "urlSetDebugMode":"https://login.microsoftonline.com/common/debugmode",
   "fEnableCssAnimation":true,
   "fAllowGrayOutLightBox":true,
   "fIsRemoteNGCSupported":true,
   "scid":1000,
   "hpgact":2000,
   "hpgid":1115,
   "pgid":"KmsiInterrupt",
   "apiCanary":"Pdh+X7wYlgY******",
   "canary":"Pdh+X7******",
   "correlationId":"e65f8de0-******",
   "sessionId":"4ea681f9-********",
   "locale":{ 
      "mkt":"en-US",
      "lcid":1033
   },
   "slMaxRetry":2,
   "slReportFailure":true,
   "strings":{ 
      "desktopsso":{ 
         "authenticatingmessage":"Trying to sign you in"
      }
   },
   "enums":{ 
      "ClientMetricsModes":{ 
         "None":0,
         "SubmitOnPost":1,
         "SubmitOnRedirect":2,
         "InstrumentPlt":4
      }
   },
   "urls":{ 
      "instr":{ 
         "pageload":"https://login.microsoftonline.com/common/instrumentation/reportpageload",
         "dssostatus":"https://login.microsoftonline.com/common/instrumentation/dssostatus"
      }
   },
   "browser":{ 
      "ltr":1,
      "_Other":1,
      "Full":1,
      "RE_Other":1,
      "b":{ 
         "name":"Other",
         "major":-1,
         "minor":-1
      },
      "os":{ 
         "name":"Unknown",
         "version":""
      },
      "V":-1
   },
   "watson":{ 
      "url":"/common/handlers/watson",
      "bundle":"https://aadcdn.msftauth.net/ests/2.1/content/cdnbundles/watson.min_v4uqqpbimbulmncaz2jdxw2.js",
      "sbundle":"https://aadcdn.msftauth.net/ests/2.1/content/cdnbundles/watsonsupport.min_3z194vh3l5oibjd0ejgm-q2.js",
      "fbundle":"https://aadcdn.msftauth.net/ests/2.1/content/cdnbundles/frameworksupport.min_zhg7it_lri4wqwee0pmhtg2.js",
      "resetErrorPeriod":5,
      "maxCorsErrors":-1,
      "maxInjectErrors":5,
      "maxErrors":10,
      "maxTotalErrors":3,
      "expSrcs":[ 
         "https://aadcdn.msauth.net/ests/",
         "https://aadcdn.msftauth.net/ests/",
         "https://login.microsoftonline.com",
         ".login.microsoftonline.com"
      ],
      "envErrorRedirect":true,
      "envErrorUrl":"/common/handlers/enverror"
   },
   "loader":{ 
      "cdnRoots":[ 
         "https://aadcdn.msauth.net/ests/",
         "https://aadcdn.msftauth.net/ests/"
      ]
   },
   "serverDetails":{ 
      "slc":"ProdSlices",
      "dc":"SIN2",
      "ri":"ESTXXXX_5",
      "ver":{ 
         "v":[ 
            2,
            1,
            9395,
            17
         ]
      },
      "rt":"2019-09-26T00:11:25",
      "et":202
   },
   "country":"JP",
   "fBreakBrandingSigninString":true,
   "urlNoCookies":"https://login.microsoftonline.com/cookiesdisabled",
   "fTrimChromeBssoUrl":true
};
//]]></script>
<script type="text/javascript">//
<*SOME JSCODE*>
    <script type="text/javascript">
        ServerData = $Config;
    </script>



    <link crossorigin="anonymous" href="https://aadcdn.msftauth.net/ests/2.1/content/cdnbundles/converged.v2.login.min_mbqre5pw01euigudkiymsa2.css" rel="stylesheet" onerror='$Loader.On(this,true)' onload='$Loader.On(this)' integrity='sha384-*******' />

    <script crossorigin="anonymous" src="https://aadcdn.msftauth.net/ests/2.1/content/cdnbundles/ux.converged.kmsi.core.min_2sdc2lgwp2zcmx1ejxk9wa2.js" onerror='$Loader.On(this,true)' onload='$Loader.On(this)' integrity='sha384-******'></script>

    <script crossorigin="anonymous" src="https://aadcdn.msftauth.net/ests/2.1/content/cdnbundles/ux.converged.kmsi.strings-en.min_pelupvyqqx7tzri2uw_ntg2.js" onerror='$Loader.On(this,true)' onload='$Loader.On(this)' integrity='sha384-********'></script>



</head>

<body data-bind="defineGlobals: ServerData, bodyCssClass" class="cb" style="display: none">
    <script type="text/javascript">//<![CDATA[
!function(){var e=window,o=e.document,i=e.$Config||{};if(e.self===e.top){o&&o.body&&(o.body.style.display="block")}else{if(!i.allowFrame){var s=e.self.location.href,l=s.indexOf("#"),n=-1!==l,t=s.indexOf("?"),f=n?l:s.length,d=-1===t||n&&t>l?"?":"&";s=s.substr(0,f)+d+"iframe-request-id="+i.sessionId+s.substr(f),e.top.location=s}}}();

//]]></script>

</body>
</html>
Response did not contain a valid SAML assertion
Please check your username and password is correct
```

**Comment by giuliocalzolari** [comment] 2019-09-27 20:26
Same here

**Comment by jessechahal** [comment] 2019-10-01 17:56
so AzureAD used to work for me. We changed our settings so a AD User could be assigned more then 1 AWS role at a given time and now AzureAD does not work for me. I noticed that there is a difference in the browser redirection flow. There is 1 extra step. You must select which role to assume in AWS. The screen is similar to https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/media/aws-multi-accounts-tutorial/tutorial_amazonwebservices%28aws%29_test_screen.png . This did not exist when the AzureAD plugin was working for me. Maybe AzureAD needs to add support for handling multiple roles/aws_accounts correctly?

**Comment by giuliocalzolari** [comment] 2019-10-01 20:48
Hi @jessechahal  I have that setup and I specify the Role as param this is my output

```
[22:37:07] gc ~ $ DUMP_CONTENT=true saml2aws login --verbose --role=arn:aws:iam::11111111111:role/AAD-Admin
DEBU[0000] Running                                       command=login
DEBU[0000] check if Creds Exist                          command=login
DEBU[0000] Expand                                        name=/Users/giuliocalzolari/.aws/credentials pkg=awsconfig
DEBU[0000] resolveSymlink                                name=/Users/giuliocalzolari/.aws/credentials pkg=awsconfig
DEBU[0000] ensureConfigExists                            filename=/Users/giuliocalzolari/.aws/credentials pkg=awsconfig
Using IDP Account default to access AzureAD https://account.activedirectory.windowsazure.com
DEBU[0000] Get credentials                               helper=osxkeychain serverURL="https://account.activedirectory.windowsazure.com"
DEBU[0000] Get credentials                               goMsg="The specified item could not be found in the keychain." helper=osxkeychain
To use saved password just hit enter.
? Username giulio.calzolari@azure.example.com
? Password **************************

DEBU[0007] building provider                             command=login idpAccount="account {\n  AppID: 51e98410-035d-4403-99bd-729ba2224ff8\n  URL: https://account.activedirectory.windowsazure.com\n  Username: giulio.calzolari@azure.example.com\n  Provider: AzureAD\n  MFA: Auto\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 3600\n  Profile: saml\n  RoleARN: arn:aws:iam::11111111111:role/AAD-Admin\n}"
Authenticating as giulio.calzolari@azure.example.com ...
POST /common/login HTTP/1.1
Host: login.microsoftonline.com
User-Agent: saml2aws/1.0 (darwin amd64) Versent
Content-Length: 1412
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip


    [omitted]
</body>
</html>
Response did not contain a valid SAML assertion
Please check your username and password is correct
```



I tried with a different tool and work prefectly !
```
aws-azure-login --profile samltest
Logging in with profile 'samltest'...
? Username: giulio.calzolari@azure.example.com
? Password: [hidden]
? Role: (Use arrow keys)
❯ arn:aws:iam::11111111111111:role/AAD-Admin
  arn:aws:iam::22222222222:role/AAD-Admin
```

**Comment by benoahriz** [comment] 2019-10-01 23:18
same issue here. +1

**Comment by rdkls** [comment] 2019-10-18 02:58
Duplicate of https://github.com/Versent/saml2aws/issues/350

Thanks @giuliocalzolari aws-azure-login works

**Comment by romanrev** [comment] 2019-11-20 23:21
I am experiencing the same issue, have to use `aws-azure-login` instead

**Comment by giuliocalzolari** [comment] 2019-11-21 09:21
I was forced to do a python script to solve the problem https://github.com/giuliocalzolari/aad-aws-login

**Closed** 2019-12-19 21:58 UTC
