### ISSUE TITLE
saml2aws fails to login to newly revamped login page

### ISSUE THREAD

**Issue by vchepkov** [Versent/saml2aws#1110] opened 2023-08-21 16:51 UTC
Attempting to login to AWS now fail with the following error:

`Failed to assume role. Please check whether you are permitted to assume the given role for the AWS service.: No accounts available.`

**Comment by pcasaes** [comment] 2023-08-21 16:53
Seeing the same here.

**Comment by djtecha** [comment] 2023-08-21 17:02
Starting today it appears that the azure login fails to return roles. This was working a few days ago with 0 changes to the saml2aws version, IAM roles, or Azure AD. Not sure if others are experiencing this caused by some change from AWS or Azure?

```
DEBU[0014] processing SAMLRequest                        provider=AzureAD
DEBU[0014] processing a SAMLResponse                     provider=AzureAD
No accounts available.
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.resolveRole
        github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:302
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.selectAwsRole
        github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:272
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login
        github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:131
main.main
        ./main.go:191
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1598
Failed to assume role. Please check whether you are permitted to assume the given role for the AWS service.
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login
        github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:133
main.main
        ./main.go:191
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1598

**Comment by ReagentX** [comment] 2023-08-21 17:02
Seems to come from:

https://github.com/Versent/saml2aws/blob/ca63a28969851e5de7c4159face407cfeecae7db/aws_account.go#L35-L57

**Comment by MichaelPalmer1** [comment] 2023-08-21 17:14
The role data can be pulled from the `<meta name="data" content="[base64 encoded json object containing role information]">`.

This makes it a lot cleaner actually.

**Comment by XSchelin** [comment] 2023-08-21 17:17
A dev at our place linked to this as a temporary workaround: https://blog.knoldus.com/how-to-make-assumerolewithsaml-calls-with-aws-cli/amp/

**Comment by jaredallard** [comment] 2023-08-21 17:24
> The role data can be pulled from the `<meta name="data" content="[base64 encoded json object containing role information]">`.
> 
> This makes it a lot cleaner actually.

Here's the full payload, if it's helpful:

```json
{
  "invalid_accounts": {},
  "RelayState": null,
  "name": null,
  "roles_accounts": {
    "accountName (accountId)": [
      "arn:aws:iam::NUMBER:role/friendly_name",
    ]
  },
  "foreign_accounts": {},
  "region": "REGION",
  "portal": null,
  "SAMLResponse": "<reallyLongString>",
  "problems": "{}",
  "policy": null
}
```

**Comment by jaredallard** [comment] 2023-08-21 17:39
If anyone wants to carry forward ^ into a PR and update the testdata, please feel free to do so. I'm about to go on an international flight, so it might take me a bit if I do it :P Consider the code to be MIT-licensed just like the repository is.

**Comment by mKeRix** [comment] 2023-08-21 17:51
Another quick workaround, in case you don't want to mess with the saml2aws code or the assume role API calls directly:

1. Open the AWS console in your browser via whatever login method you use for the account you want to access.
2. Open CloudShell. 
![Screen Shot 2023-08-21 at 19 47 01](https://github.com/Versent/saml2aws/assets/770596/61372197-be70-46be-b1c4-e0f7fdf26c2e)
3. Type `aws configure export-credentials --format env`.
4. Copy the resulting output into your shell.

**Comment by ReagentX** [comment] 2023-08-21 17:51
It appears the login page update was rolled back on the AWS side.

**Comment by jaredallard** [comment] 2023-08-21 17:56
> It appears the login page update was rolled back on the AWS side.

I was a little worried about that. It makes supporting it a little more painful since we won't be able to get a good test without the live page... 😢 

We probably want to support both methods in a PR in case it switches back and forth again, too.

**Comment by djtecha** [comment] 2023-08-21 18:43
Great rally though!

**Comment by andrea-l-conway** [comment] 2023-08-21 18:49
Here is a sample of the HTML for the role table:

```
<ul class="saml-form_custom_list__LuP_V">
    <li class="saml-form_custom_list_item__H1wPE">
    <div class="flex flex-row">
        <div class="flex-grow">
        <div class="saml-form_account_name_div__dDGkX">aws-account-1 </div>
        <div class="saml-form_account_id_div__Q1PBA">1234-5678-9012</div>
        <div class="saml-form_account_role_div__FhQmy">
            <div class="saml-form_role_div__BeMu2">
            <a class="saml-form_role_text__Cfxwn" id="arn:aws:iam::123456789012:role/AWS-IAM-Role-Name" data-testid="roleLink-arn:aws:iam::123456789012:role" role="button" aria-label="Account ID 1234-5678-9012 Role Name AWS-IAM-Role-Name" tabindex="0">AWS-IAM-Role-Name</a>
            <p class="saml-form_space__uJWq3"></p>
            </div>
            <div class="saml-form_role_div__BeMu2">
            <a class="saml-form_role_text__Cfxwn" id="arn:aws:iam::123456789012:role/AWS-IAM-Role-Name" data-testid="roleLink-arn:aws:iam::123456789012:role" role="button" aria-label="Account ID 1234-5678-9012 Role Name AWS-IAM-Role-Name" tabindex="0">AWS-IAM-Role-Name</a>
            <p class="saml-form_space__uJWq3"></p>
            </div>
            <div class="saml-form_role_div__BeMu2">
            <a class="saml-form_role_text__Cfxwn" id="arn:aws:iam::123456789012:role/AWS-IAM-Role-Name" data-testid="roleLink-arn:aws:iam::123456789012:role" role="button" aria-label="Account ID 1234-5678-9012 Role Name AWS-IAM-Role-Name" tabindex="0">AWS-IAM-Role-Name</a>
            <p class="saml-form_space__uJWq3"></p>
            </div>
            <div class="saml-form_role_div__BeMu2">
            <a class="saml-form_role_text__Cfxwn" id="arn:aws:iam::123456789012:role/AWS-IAM-Role-Name" data-testid="roleLink-arn:aws:iam::123456789012:role" role="button" aria-label="Account ID 1234-5678-9012 Role Name AWS-IAM-Role-Name" tabindex="0">AWS-IAM-Role-Name</a>
            </div>
        </div>
        </div>
    </div>
    </li>
    <li class="saml-form_custom_list_item__H1wPE">
    <div class="flex flex-row">
        <div class="flex-grow">
        <div class="saml-form_account_name_div__dDGkX">aws-account-2 </div>
        <div class="saml-form_account_id_div__Q1PBA">1234-5678-9012</div>
        <div class="saml-form_account_role_div__FhQmy">
            <div class="saml-form_role_div__BeMu2">
            <a class="saml-form_role_text__Cfxwn" id="arn:aws:iam::123456789012:role/AWS-IAM-Role-Name" data-testid="roleLink-arn:aws:iam::123456789012:role" role="button" aria-label="Account ID 1234-5678-9012 Role Name AWS-IAM-Role-Name" tabindex="0">AWS-IAM-Role-Name</a>
            <p class="saml-form_space__uJWq3"></p>
            </div>
            <div class="saml-form_role_div__BeMu2">
            <a class="saml-form_role_text__Cfxwn" id="arn:aws:iam::123456789012:role/AWS-IAM-Role-Name" data-testid="roleLink-arn:aws:iam::123456789012:role" role="button" aria-label="Account ID 1234-5678-9012 Role Name AWS-IAM-Role-Name" tabindex="0">AWS-IAM-Role-Name</a>
            <p class="saml-form_space__uJWq3"></p>
            </div>
            <div class="saml-form_role_div__BeMu2">
            <a class="saml-form_role_text__Cfxwn" id="arn:aws:iam::123456789012:role/AWS-IAM-Role-Name" data-testid="roleLink-arn:aws:iam::123456789012:role" role="button" aria-label="Account ID 1234-5678-9012 Role Name AWS-IAM-Role-Name" tabindex="0">AWS-IAM-Role-Name</a>
            <p class="saml-form_space__uJWq3"></p>
            </div>
            <div class="saml-form_role_div__BeMu2">
            <a class="saml-form_role_text__Cfxwn" id="arn:aws:iam::123456789012:role/AWS-IAM-Role-Name" data-testid="roleLink-arn:aws:iam::123456789012:role" role="button" aria-label="Account ID 1234-5678-9012 Role Name AWS-IAM-Role-Name" tabindex="0">AWS-IAM-Role-Name</a>
            </div>
        </div>
        </div>
    </div>
    </li>
</ul>
```

And here is a sample of the JSON blob in `<meta name="data" content="[base64 blob]">` after base64 decoding:

```
{
  "invalid_accounts": {},
  "RelayState": "",
  "name": null,
  "roles_accounts": {
    "aws-account-1 (123456789012)": [
      "arn:aws:iam::123456789012:role/AWS-IAM-Role-Name",
      "arn:aws:iam::123456789012:role/AWS-IAM-Role-Name",
      "arn:aws:iam::123456789012:role/AWS-IAM-Role-Name",
      "arn:aws:iam::123456789012:role/AWS-IAM-Role-Name"
    ],
    "aws-account-2 (123456789012)": [
      "arn:aws:iam::123456789012:role/AWS-IAM-Role-Name",
      "arn:aws:iam::123456789012:role/AWS-IAM-Role-Name",
      "arn:aws:iam::123456789012:role/AWS-IAM-Role-Name",
      "arn:aws:iam::123456789012:role/AWS-IAM-Role-Name"
    ]
  },
  "foreign_accounts": {},
  "region": "IAD",
  "portal": null,
  "SAMLResponse": "SGVsbG8sIFdvcmxkIQ==",
  "problems": "{}",
  "policy": null
}
```

**Comment by joepurdy** [comment] 2023-08-21 23:27
I'm the author of the PR to implement a fix for gimme-aws-creds and I wanted to drop a note here that if it helps folks working to patch saml2aws, I did dump the new NextJS sign-in page before AWS rolled back earlier today. I have that saved as a sanitized mock file for use as a fixture for the tests for gimme-aws-creds. Since my PR hasn't landed yet you can get to the file at https://github.com/joepurdy/gimme-aws-creds/blob/fix/425/aws-saml-parsing/tests/fixtures/aws_nextjs.html

Hope that helps author a patch for saml2aws 🫡

**Comment by rr-jianan-lei** [comment] 2023-08-22 18:16
Can we parse the saml assertion to get the roles not depending on the frontend?
Something like:
```
import (
    "encoding/xml"
    "github.com/crewjam/saml"
)

roles := []string{}
var response saml.Response
err := xml.Unmarshal(data, & response)
if err != nil {
    return []string{}, fmt.Errorf("error unmarshal saml assertion")
}
	
for _, attributeStatement := range response.Assertion.AttributeStatements {
    for _, attribute := range attributeStatement.Attributes {
        if attribute.Name == "https://aws.amazon.com/SAML/Attributes/Role" {
	    for _, attributeValue := range attribute.Values {
		roles = append(roles, attributeValue.Value)
	    }
	}
    }
}
```
We can still get AWS account names from frontend. Just a thought.

**Comment by tinaboyce** [comment] 2023-12-24 05:44
@vchepkov (and anyone who is interested in this issue), for house-keeping, are you still experiencing this issue?

**Comment by vchepkov** [comment] 2023-12-24 17:32
I am not, but only because AWS rolled back the changes and never re-applied them again

**Comment by tinaboyce** [comment] 2023-12-27 14:34
Thanks for the follow up @vchepkov and thanks everyone for this input. Let's hope it was just a mistake that won't regress.

To everyone, I'll close it for now.

**Closed by tinaboyce** 2023-12-27 14:34 UTC
