### ISSUE TITLE
Cannot set a profile other than "saml"  as `--profile`is deprecated and docs are empty

### ISSUE THREAD

**Issue by benjackwhite** [Versent/saml2aws#251] opened 2018-11-21 10:29 UTC
Adding the `--profile` flag throws an error saying that it is deprecated and to see "https://github.com/Versent/saml2aws#adding-idp-accounts" but this link goes nowhere.

How can you set the aws_profile to something other than "saml" with --skip-prompt enabled?

**Comment by acobaugh** [comment] 2018-11-27 02:38
`saml2aws login --profile foo --skip-prompt` works for me. What version were you testing with?

**Comment by benjackwhite** [comment] 2018-11-27 10:00
Ahhhh okay. I think I understand now. I was giving it to the "configure" command but that is only for the login one. Thanks for the hint!

**Comment by micahlmartin** [comment] 2019-02-08 04:34
Is there a reason the `--profile` flag isn't used during configure? It can be actually stored in the config so I would think it should be.

**Comment by acobaugh** [comment] 2019-02-08 04:41
Nope, that seems reasonable.

**Comment by sagar-srivastava** [comment] 2019-02-28 00:00
I think the issue is that configure command always updates the same profile 'saml' section of the .saml2aws, which inturn will always update the aws cli profile 'saml' which is not desirable in a multi accouint environment. Its better if there is a ways in the saml2aws configure to set the --aws-profile value to something other than 'saml' That way no manual modification of .saml2aws will be needed for multi profiles.

**Comment by acobaugh** [comment] 2019-02-28 00:21
This should be fixed once #279 is merged.

**Comment by micahlmartin** [comment] 2019-03-11 15:37
This is now available via the `--profile` option. This issue can be closed.

**Comment by kwhitlock** [comment] 2019-04-03 10:29
Hi @micahlmartin - I'm not sure the `--profile` option works with configure. I'm running 2.13.0 Still comes up with `unknown long flag`

```
PS Z:\> saml2aws --version
2.13.0
PS Z:\> saml2aws configure --idp-account <omitted> --idp-provider ADFS --mfa Auto --username <omitted> --url <omitted> --aws-urn <omitted> --role <omitted> --profile default --skip-prompt
saml2aws.exe: error: unknown long flag '--profile', try --help
```

Did I misunderstand something? 

Cheers!

**Closed** 2023-11-18 23:50 UTC
